### ISSUE TITLE
Unable to set timezone on Debian (solution: install `dbus`)

### ISSUE THREAD

**Issue by bluemalkin** [saltstack-formulas/timezone-formula#11]
On Debian Stretch:

```
timezone:
  name: 'Australia/Sydney'
  utc: false
```

Results in:
```
----------
          ID: timezone_setting
    Function: timezone.system
        Name: Australia/Sydney
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 73, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 389, in get_hwclock
                  ret = _timedatectl()
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 54, in _timedatectl
                  raise CommandExecutionError(msg)
              CommandExecutionError: timedatectl failed: Failed to create bus connection: No such file or directory
     Started: 10:45:55.406716
    Duration: 12.129 ms
     Changes:
```

**Comment by myii** [comment]
@bluemalkin It's working on my Debian Stretch docker-based minion using the following pillar:

```sls
timezone:
  lookup:
    name: 'Australia/Sydney'
    utc: False
```

Result:

```salt
debian_develop:
----------
          ID: timezone_setting
    Function: timezone.system
        Name: Australia/Sydney
      Result: True
     Comment: Set timezone Australia/Sydney
     ...
     Changes:   
              ----------
              timezone:
                  Australia/Sydney
----------
          ID: timezone_packages
    Function: pkg.installed
        Name: tzdata
      Result: True
     Comment: All specified packages are already installed
     ...
----------
          ID: timezone_symlink
    Function: file.symlink
        Name: /etc/localtime
      Result: True
     Comment: Symlink /etc/localtime is present and owned by root:root
     ...
```

**Comment by myii** [comment]
```salt
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/timezone/init.sls:
# This state configures the timezone.


timezone_setting:
  timezone.system:
    - name: Australia/Sydney
    - utc: False

timezone_packages:
  pkg.installed:
    - name: tzdata

timezone_symlink:
  file.symlink:
    - name: /etc/localtime
    - target: /usr/share/zoneinfo/Australia/Sydney
    - force: true
    - require:
      - pkg: tzdata
```

**Comment by myii** [comment]
```salt
# salt --versions-report
Salt Version:
           Salt: 2019.2.0-n/a-2fe27f5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-66-generic
         system: Linux
        version: debian 9.9
```

Perhaps a `py2` issue?

**Comment by myii** [comment]
@bluemalkin Nope, all working on `debian-9-2018-3-py2` as well.

```salt
# salt-minion --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-66-generic
         system: Linux
        version: debian 9.9
```

```salt
debian-9-2018-3-py2:
----------
          ID: timezone_setting
    Function: timezone.system
        Name: Australia/Sydney
      Result: True
     Comment: Set timezone Australia/Sydney
     ...
     Changes:   
              ----------
              timezone:
                  Australia/Sydney
----------
          ID: timezone_packages
    Function: pkg.installed
        Name: tzdata
      Result: True
     Comment: All specified packages are already installed
     ...
----------
          ID: timezone_symlink
    Function: file.symlink
        Name: /etc/localtime
      Result: True
     Comment: Symlink /etc/localtime is present and owned by root:root
     ...
```

**Comment by bluemalkin** [comment]
I get the same on my 2 GCP debian VMs on GCP. Salt is bootstrapped with `https://bootstrap.saltstack.com`

Some info:
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8
```

**Comment by myii** [comment]
@bluemalkin Does this help?

* https://github.com/solita/docker-systemd/issues/12#issuecomment-368505313

From my container:

```bash
# dpkg -l | grep dbus
ii  dbus                        1.10.28-0+deb9u1               amd64        simple interprocess messaging system (daemon and utilities)
ii  libdbus-1-3:amd64           1.10.28-0+deb9u1               amd64        simple interprocess messaging system (library)
ii  libdbus-glib-1-2:amd64      0.108-2                        amd64        simple interprocess messaging system (GLib-based shared library)
ii  libnih-dbus1                1.0.3-8                        amd64        NIH D-Bus Bindings Library
ii  python-dbus                 1.2.4-1+b1                     amd64        simple interprocess messaging system (Python interface)
```

**Comment by myii** [comment]
And to go along with that previous comment:

```bash
# timedatectl status
      Local time: Wed 2019-07-24 16:09:32 AEST
  Universal time: Wed 2019-07-24 06:09:32 UTC
        RTC time: Wed 2019-07-24 06:09:32
       Time zone: Australia/Sydney (AEST, +1000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by bluemalkin** [comment]
Can confirm that installing `dbus` package fixes the issue. Thank you !

**Comment by myii** [comment]
Whoa, not so fast!  Now we need to figure out if `dbus` needs to be included as a requirement in this formula.  If so, we'll need a PR to fix this up.  Thanks for uncovering this issue in the first place.

CC: @aboe76 @javierbertoli.

**Comment by javierbertoli** [comment]
Well, it seems that:

* this formula uses the [timezone.system](https://github.com/saltstack/salt/blob/develop/salt/states/timezone.py#L43) state, which
* [calls](https://github.com/saltstack/salt/blob/develop/salt/states/timezone.py#L62) the [timezone module](https://github.com/saltstack/salt/blob/develop/salt/modules/timezone.py), which
* calls the system's [timedatectl](https://github.com/saltstack/salt/blob/develop/salt/modules/timezone.py#L50), which 
* apparently uses DBUS to communicate with systemd's *timedated* (see [here](https://bugs.launchpad.net/snappy/+bug/1650688/comments/18) and [here](https://github.com/Microsoft/WSL/issues/869#issuecomment-391956199))

In reply to the comment:

> we need to figure out if dbus needs to be included as a requirement in this formula

I'd say 'No':

*dbus* is a requirement for *timedatectl*, which in Debian is part of the *systemd* package
```bash
dlocate timedatectl
systemd: /usr/bin/timedatectl
```
which has *dbus* marked as a dependency
```bash
apt-cache showpkg systemd
...
Dependencies: 
... dbus (0 (null)) ...
```
A simple test shows it should be installed in a Debian VM:

```bash
docker run -ti debian:9 /bin/bash
root@f55177204e2a:/# dpkg -l |grep dbus
root@f55177204e2a:/#
...
root@f55177204e2a:/# apt update; apt install systemd
...
The following additional packages will be installed:
  cgmanager dbus dmsetup...
```


I guess the real question here is *WHY* dbus is not running/installed in @bluemalkin 's VMs? Are these docker instances? Apparently, they [require to run with some different parameters to get them responding](https://stackoverflow.com/a/46837044)

**Comment by myii** [comment]
@javierbertoli Thanks for the extensive breakdown, educational as usual!  As far as I'm aware, this is the VM in use:

* https://console.cloud.google.com/marketplace/details/google/debian9

Besides that, I've labelled this with `wontfix`, so that we can go ahead and close it once we're done.  @bluemalkin Would you be able to try out the paramaters @javierbertoli has linked to in the comment above?

**Comment by bluemalkin** [comment]
There's no Docker involved.

This is the GCP Debian image, e.g. `projects/debian-cloud/global/images/debian-9-stretch-v20190618`
And it has no dbus:
```
$ dpkg -l | grep dbus
$
```

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by mgomersbach** [comment]
I guess this Dbus dependency only applies on distributions that have SystemD.
The formula fails for me in certain setups where there is no Dbus needed.
In [here](https://github.com/saltstack/salt/blob/develop/salt/modules/timezone.py#L178-L207 ) the individual ways are covered.

**Comment by myii** [comment]
@bluemalkin After all of that, we ended up needing `dbus` after all:

https://github.com/saltstack-formulas/timezone-formula/blob/a201d088e1553b2970811826100434a1ce9a17a8/timezone/init.sls#L28-L42

So closing this issue as fixed.  Thanks for the initial report.  Thanks to @mgomersbach for reminding me that this issue was still open!
